### PR TITLE
hyphen separated suave.eth.remote_endpoint

### PR DESCRIPTION
**Pull request by jinmel**
- conforms with other suave flags

## 📚 References

---

* [x] I have seen and agree to CONTRIBUTING.md

### CODE REVIEW

**Review by ferranbt — COMMENTED** [review]
Could you keep both flags for now? I am okay with the change but it is not backwards compatible.

**Comment by jinmel** [comment]
@ferranbt Do you mean we use both `suave.eth.remote-backend` and `suave.eth.remote_backend` ?

**Comment by ferranbt** [comment]
> @ferranbt Do you mean we use both `suave.eth.remote-backend` and `suave.eth.remote_backend` ?

Yes

**Comment by jinmel** [comment]
closing as #196 handles it

**Pull request closed without merging**
